site:
  name: "Pho Thin"
  description: "Personal Blog"
  author: "Pho Thin Maung"
  locale: 'en-US'
  keywords:
    - Blog
    - Personal
social:
  github:
  twitter:
  facebook:
og:
  type: "Blog"
  image:
directories:
  markdown: "posts"
  images: "img"
  style: "style"
